### ISSUE TITLE
Is there are codes available for evaluations on the paper?

### ISSUE THREAD

**Issue by spk921** [deep-geometry/abc-dataset#3]
Could you share the codes which are used on the paper for analytic methods? 

"Robust Statistical Estimation on Discrete Surfaces (RoSt) [37] operating on point clouds (PC), and meshes (M), Osculating Jets
(Jets) [23], also on point clouds and meshes, and Uniform
weighting of adjacent face normals (Uniform) [36]."

**Comment by skoch9** [comment]
Hi, 

yes there is code available for the methods. 

The code for RoSt, we obtained from the authors of the paper, so you need to contact them or I can check if we can supply this. 

For Osculating Jets we use the "original" implementation from CGAL, see the examples [Jet_fitting_3/Mesh_estimation](https://doc.cgal.org/latest/Jet_fitting_3/index.html) for meshes and [Point_set_processing_3/normal_estimation](https://doc.cgal.org/latest/Point_set_processing_3/Point_set_processing_3_2normals_example_8cpp-example.html) for point clouds. Check their repository to find the examples. We used the version 4.13.

For Uniform we applied the implementation from [libigl](https://github.com/libigl/libigl/blob/master/include/igl/per_vertex_normals.h).

Let me know if you need to know further details.
